config/routes.rb
Rails.application.routes.draw do

  get 'reviews/create'

  get 'reviews/destroy'
  get 'restaurants/all', to: 'restaurants#all'

  root 'white_pages#home'
  resources :restaurants do
    resources :reservations, only: [:create, :destroy, :index]
    resources :reviews, only: [:create, :destroy]
  end

  resources :users
  resources :patrons, only: [:create, :destroy, :show]
  resources :owners, only: [:create, :destroy, :show]
  resources :sessions, only: [:new, :create, :destroy]

end

app/models/owner.rb
class Owner < User
end

app/models/patron.rb
class Patron < User
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
	belongs_to :user
	belongs_to :restaurant

	after_create :add_user_points
	after_destroy :remove_user_points

	def remove_user_points
		self.user.loyalty_points -= self.guest_count * 20
	end

	def add_user_points
		self.user.loyalty_points += self.guest_count * 10
	end

	def available?(party_size, date)
		restaurant.reservations.where(date: date).sum(:guest_count) + party_size <= 100
	end

	def already_reserved?(date, user)
		restaurant.reservations.where(date: date, user_id: user.id).exists?
	end
	
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	belongs_to :user
	has_many :reservations
	has_many :reviews

	validates :name, presence: true
	validates :address, presence: true
	validates :price_range, presence: true
	validates :summary, presence: true

	geocoded_by :get_address 
	before_save :geocode #auto-fetches coordinates

	def self.top4
		self.all.sample(4)
	end

	def get_address
		self.address
	end
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :user
	belongs_to :restaurant
end

app/models/user.rb
class User < ActiveRecord::Base
	
	has_secure_password

	has_many :restaurants
	has_many :reservations
	has_many :reviews

	validates :email, presence: true, uniqueness: { case_sensitive: false }
	validates :password, presence: true, confirmation: true, length: { minimum: 5 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_login
  	unless current_user
  		flash[:alert] = 'You must login'
  		redirect_to new_user_path
  	end
  end

  helper_method :current_user
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController

	def create
		@owner = Owner.new(owner_params)

		if @owner.save 
			WelcomeMailer.welcome_email(@owner).deliver
			session[:user_id] = @owner.id
			flash[:notice] = 'Account successfully created'
			redirect_to @owner
		else
			flash[:alert] = 'There has been an error'
			redirect_to new_user_path
		end
	end

	def show
		@restaurants = Restaurant.where(user_id: params[:id])
	end

	def destroy
	end

	private

	def owner_params
		params.require(:owner).permit(:email, :password, :password_confirmation)
	end
end

app/controllers/patrons_controller.rb
class PatronsController < ApplicationController

	def create
		@patron = Patron.new(patron_params)

		if @patron.save 
			session[:user_id] = @patron.id
			flash[:notice] = 'Account successfully created'
			redirect_to root_path
		else
			flash[:alert] = 'There has been an error'
			redirect_to new_user_path
		end
	end

	def show
		@reservations = current_user.reservations.order('date DESC')
	end

	def destroy
	end

	private

	def patron_params
		params.require(:patron).permit(:email, :password, :password_confirmation)
	end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

	def index
		@distance = params[:miles]
		@price = params[:price]
		@restaurants = Restaurant.near(params[:q],@distance).where(price_range: @price)
	end

	def all
		@restaurants = if params[:search]
			Restaurant.where("LOWER(name) LIKE LOWER(?)", "%#{params[:search]}%").page(params[:page])
		else
			Restaurant.order('restaurants.name ASC').page(params[:page])
		end

		respond_to do |format| 
			format.html
			format.js 
		end

	end

	def new
		@restaurant = Restaurant.new
	end

	def create
		@restaurant = current_user.restaurants.build(restaurant_params)
		if @restaurant.save
			redirect_to current_user
		else
			render :new 
		end
	end

	def show
		@restaurant = Restaurant.find(params[:id])
		@reservation = Reservation.new
		@review = Review.new
	end	

	private

	def restaurant_params
		params.require(:restaurant).permit(:name, :address, :price_range, :summary, :restaurant)
	end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :require_login

  def create
  	@review = current_user.reviews.build(review_params)
    @review.restaurant_id = params[:restaurant_id]
    @review.save
    redirect_to restaurant_path(@review.restaurant_id)
  end

  def destroy
  end

  private

  def review_params
  	params.require(:review).permit(:body, :user_id, :restaurant_id, :rating)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		user = User.find_by(email: params[:email])
		if user && user.authenticate(params[:password])
			session[:user_id] = user.id
			if user.type == 'Patron'
				redirect_to root_path, notice: 'successfully signed in'
			else
				redirect_to user, notice: 'successfully signed in'
			end
		else
			flash.now[:alert] = "invalid email or password"
			render :new
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to root_url
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@patron = Patron.new
		@owner = Owner.new
	end

	def show
		@restaurants = current_user.restaurants
		@reservations = current_user.reservations
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		user = User.find(params[:id])
		@user = user.update(user_params)
		if @user.save
			redirect_to @user, notice: "Information successfully updated"
		else
			render :edit, alert: "Please fill out valid information"
		end
	end

	private

	def user_params
		params.require(:user).permit(:email, :password, :password_confirmation)
	end

end

app/controllers/white_pages_controller.rb
class WhitePagesController < ApplicationController

	def home
		@top4 = Restaurant.top4
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/owner_helper.rb
module OwnerHelper
end

app/helpers/patron_helper.rb
module PatronHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/white_pages_helper.rb
module WhitePagesHelper
end

app/views/owners/show.html.erb
<div class='new-restaurant-button'>
	<%= link_to 'Add Restaurant', new_restaurant_path, class: 'button expand'%>
</div>

<h3>Signed in as: <%= current_user.email %></h3>

<p>My Restaurants</p>

<ul class='small-block-grid-3 center'>
	<% unless @restaurants.empty? %>
		<% @restaurants.each do |restaurant| %>
			<li>
				<h5><%= restaurant.name %></h5>
				<%= link_to 'Reservations', restaurant_reservations_path(restaurant), class: 'button tiny' %>
			</li>
		<% end %>
	<% end %>
</ul>

app/views/patrons/show.html.erb
<h4 class='center'>Loyalty Points: <%= current_user.loyalty_points %></h4>

<h3 class='center'>My Reservations</h3>

<% unless @reservations.empty? %>
	<div class='user-show'>
		<% @reservations.each do |reservation| %>
			<div class='panel center'>
				<p><strong>Restaurant: </strong><%= reservation.restaurant.name %></p>
				<p><strong>Address: </strong><%= reservation.restaurant.address %></p>
				<p><strong>Date: </strong><%= reservation.date.to_date %></p>
				<p><strong>Guests: </strong><%= reservation.guest_count %></p>
				<%= link_to 'Delete Reservation', restaurant_reservation_path(reservation.restaurant.id, reservation.id), method: 'delete', class: 'button tiny' %></p>
			</div>
		<% end %>
	</div>
<% end %>

app/views/restaurants/_restaurant.html.erb
<p><%= link_to "#{restaurant.name}", restaurant_path(restaurant.id) %></p>
<p><%= truncate(restaurant.summary, length: 100) %></p>

app/views/restaurants/all.html.erb
<div class='name-form'>
	<%= form_tag restaurants_path, method: :get, authentication: false, id: 'search-form' do %>
		<%= text_field_tag :search, params[:search] %>
		<%= submit_tag "Refine Search", class: 'button tiny' %>
	<% end %>
</div>



<div id='restaurants-all'>
	<h2><small><%= page_entries_info @restaurants %></small></h2>

	<%= render @restaurants %>

	<%= paginate @restaurants %>
</div>

app/views/restaurants/all.js.erb
$('#restaurants-all').append( "<%= j(render @restaurants) %>" )

app/views/restaurants/index.html.erb
<%= form_tag restaurants_path, method: :get, authentication: false, id: 'search-form' do %>
	<%= text_field_tag :search, params[:search] %>
	<%= submit_tag 'Search' %>
<%= end %>

<h5>Restaurants within <%= @distance %> miles of your location, in the <%= @price %> price range.</h5>
<ul>
		<li class='close-restaurants'><%= link_to "#{restaurant.name}", restaurant %></li>
	<% end %>
</ul>

app/views/restaurants/new.html.erb
<% if @restaurant.errors.any? %>
	<div id='error_explanation'>
		<h3><%= pluralize(@restaurant.errors.count, 'error') %> prohibited the restaurant from being saved:</h3>

		<ul>
			<% @restaurant.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
<% end %>

<div class='new-form'>
	<fieldset>
		<legend>Create a new restaurant</legend>
		<%= form_for @restaurant do |f| %>
			<%= f.text_field :name, placeholder: 'Name' %>
			<%= f.text_field :address, placeholder: 'Address' %>
			<%= f.select :price_range, options_for_select(['$10-$20', '$20-$30','$30-$40','$40+']), prompt: 'Average entree price'  %>
			<%= f.text_area :summary, placeholder: 'Restaurant Description' %>
			<%= f.submit 'Add Restaurant', class: 'button tiny' %>
		<% end %>
	</fieldset>
</div>

app/views/restaurants/show.html.erb
<p><%= flash[:alert] %></p>

<div class='restaurant-show'>
<div class='large-6 columns center'>
		<h1 class='center'><%= @restaurant.name %></h1>
		<h6><strong>Address</strong></h6>
		<p><%= @restaurant.address%></p>
		<h6><strong>Price</strong></h6>
		<p><%= @restaurant.price_range%></p>
		<h6><strong>Description</strong></h6>
		<p><%= @restaurant.summary%></p>
	</div>
</div>

<div class='large-6 columns'>
	<fieldset>
		<legend>Reserve a spot!</legend>
		<%= form_for [@restaurant, @reservation] do |f| %>
			<%= select_datetime(Time.now, prefix: 'reservation', discard_minute: true, ampm: true) %>
			<%= f.select :guest_count, (2..15), prompt: 'Number of guests' %>
			<%= f.submit 'Reserve!', class: 'button tiny' %>
		<% end %>
	</fieldset>
</div>
</div>

<div class='reviews center'>
	<h3>Reviews</h3>
	<% unless @restaurant.reviews.empty? %>
		<% @restaurant.reviews.each do |review| %>
			<div class='panel'>
				<p><% review.rating.times do %>
					&#9733
					<% end %></p>
				<%= review.body %></p>
			</div>
		<% end %>
	<% end %>
</div>

<div class='center'>
	<fieldset class='review'>
		<legend>Add Review</legend>
		<%= form_for [@restaurant, @review] do |f| %>
			<%= f.select :rating, (1..5), prompt: 'Rating' %>
			<%= f.text_area :body %>
			<%= f.submit 'Post', class: 'button tiny' %>
		<% end %>
	</fieldset>
</div>

app/views/users/edit.html.erb
<div class='new-form'>
	<fieldset>
		<legend>Edit Information</legend>
		<%= form_for @user, "/users/#{@user.id}" do |f| %>
			<%= f.text_field :email, placeholder: 'email' %>
			<%= f.password_field :password, placeholder: 'password' %>
			<%= f.password_field :password_confirmation, placeholder: 'password_confirmation' %>
			<%= f.submit 'Sign up', class: 'button tiny' %>
		<% end %>
	</fieldset>
</div>

app/views/users/new.html.erb
<% if @patron.errors.any? %>
	<div id='error_explanation'>
		<h3><%= pluralize(@patron.errors.count, 'error') %> prohibited the sign up</h3>

		<ul>
			<% @patron.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
<% end %>


<div class='new-form'>
	<fieldset>
		<legend>User Sign Up</legend>
		<%= form_for @patron do |f| %>
			<%= f.text_field :email, placeholder: 'email' %>
			<%= f.password_field :password, placeholder: 'password' %>
			<%= f.password_field :password_confirmation, placeholder: 'password_confirmation' %>
			<%= f.submit 'Sign up', class: 'button tiny' %>
		<% end %>
	</fieldset>
</div>

<div class='new-form'>	
	<fieldset>
	<legend>Restaurant Owner Sign Up</legend>
	<%= form_for @owner do |f| %>
		<%= f.text_field :email, placeholder: 'email' %>
		<%= f.password_field :password, placeholder: 'password' %>
		<%= f.password_field :password_confirmation, placeholder: 'password_confirmation' %>
		<%= f.submit 'Sign up', class: 'button tiny' %>
	<% end %>
	</fieldset>
</div>

app/views/users/show.html.erb
<h2><%= current_user.email %></h2>

<p>My Reservations</p>

<% unless @reservations.empty? %>
	<% @reservations.each do |reservation| %>
		<p><%= "#{reservation.restaurant.name}, #{reservation.restaurant.address}, #{reservation.date}, #{reservation.guest_count} guests" %><%= link_to 'Delete Reservation', restaurant_reservation_path(reservation.restaurant.id, reservation.id), method: 'delete' %></p>
	<% end %>
<% end %>

<p>My Restaurants</p>

<% unless @restaurants.empty? %>
	<% @restaurants.each do |restaurant| %>
		<%= link_to "#{restaurant.name}", restaurant_path(restaurant) %>
	<% end %>
<% end %>