config/routes.rb
Rails.application.routes.draw do

  get 'reviews/create'

  get 'reviews/destroy'
  get 'restaurants/all', to: 'restaurants#all'

  root 'white_pages#home'
  resources :restaurants do
    resources :reservations, only: [:create, :destroy, :index]
    resources :reviews, only: [:create, :destroy]
  end

  resources :users
  resources :patrons, only: [:create, :destroy, :show]
  resources :owners, only: [:create, :destroy, :show]
  resources :sessions, only: [:new, :create, :destroy]

end

app/models/owner.rb
class Owner < User
end

app/models/patron.rb
class Patron < User
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
	belongs_to :user
	belongs_to :restaurant

	after_create :add_user_points
	after_destroy :remove_user_points

	def remove_user_points
		self.user.loyalty_points -= self.guest_count * 20
	end

	def add_user_points
		self.user.loyalty_points += self.guest_count * 10
	end

	def available?(party_size, date)
		restaurant.reservations.where(date: date).sum(:guest_count) + party_size <= 100
	end

	def already_reserved?(date, user)
		restaurant.reservations.where(date: date, user_id: user.id).exists?
	end
	
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	belongs_to :user
	has_many :reservations
	has_many :reviews

	validates :name, presence: true
	validates :address, presence: true
	validates :price_range, presence: true
	validates :summary, presence: true

	geocoded_by :get_address 
	before_save :geocode #auto-fetches coordinates

	def self.top4
		self.all.sample(4)
	end

	def get_address
		self.address
	end
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :user
	belongs_to :restaurant
end

app/models/user.rb
class User < ActiveRecord::Base
	
	has_secure_password

	has_many :restaurants
	has_many :reservations
	has_many :reviews

	validates :email, presence: true, uniqueness: { case_sensitive: false }
	validates :password, presence: true, confirmation: true, length: { minimum: 5 }

end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController

	def create
		@owner = Owner.new(owner_params)

		if @owner.save 
			WelcomeMailer.welcome_email(@owner).deliver
			session[:user_id] = @owner.id
			flash[:notice] = 'Account successfully created'
			redirect_to @owner
		else
			flash[:alert] = 'There has been an error'
			redirect_to new_user_path
		end
	end

	def show
		@restaurants = Restaurant.where(user_id: params[:id])
	end

	def destroy
	end

	private

	def owner_params
		params.require(:owner).permit(:email, :password, :password_confirmation)
	end
end

app/controllers/patrons_controller.rb
class PatronsController < ApplicationController

	def create
		@patron = Patron.new(patron_params)

		if @patron.save 
			session[:user_id] = @patron.id
			flash[:notice] = 'Account successfully created'
			redirect_to root_path
		else
			flash[:alert] = 'There has been an error'
			redirect_to new_user_path
		end
	end

	def show
		@reservations = current_user.reservations.order('date DESC')
	end

	def destroy
	end

	private

	def patron_params
		params.require(:patron).permit(:email, :password, :password_confirmation)
	end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :require_login

  def create
  	@review = current_user.reviews.build(review_params)
    @review.restaurant_id = params[:restaurant_id]
    @review.save
    redirect_to restaurant_path(@review.restaurant_id)
  end

  def destroy
  end

  private

  def review_params
  	params.require(:review).permit(:body, :user_id, :restaurant_id, :rating)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		user = User.find_by(email: params[:email])
		if user && user.authenticate(params[:password])
			session[:user_id] = user.id
			if user.type == 'Patron'
				redirect_to root_path, notice: 'successfully signed in'
			else
				redirect_to user, notice: 'successfully signed in'
			end
		else
			flash.now[:alert] = "invalid email or password"
			render :new
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to root_url
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@patron = Patron.new
		@owner = Owner.new
	end

	def show
		@restaurants = current_user.restaurants
		@reservations = current_user.reservations
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		user = User.find(params[:id])
		@user = user.update(user_params)
		if @user.save
			redirect_to @user, notice: "Information successfully updated"
		else
			render :edit, alert: "Please fill out valid information"
		end
	end

	private

	def user_params
		params.require(:user).permit(:email, :password, :password_confirmation)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/owner_helper.rb
module OwnerHelper
end

app/helpers/patron_helper.rb
module PatronHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/white_pages_helper.rb
module WhitePagesHelper
end

app/views/layouts/_header.html.erb
<% if current_user && current_user.type == 'Owner' %>
  <nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to 'OpenTable', root_path %></h1>
    </li>
    <li class='toggle-topbar menu-icon'><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">

    <ul class="right">
      <% if current_user %>
        <li class="has-dropdown">
          <%= link_to 'My Account', '#' %>  
          <ul class="dropdown">
            <li><%= link_to 'Profile', current_user %>  </li>
            <li></li>
            <li><%= link_to 'Sign out', session_path(current_user), method: 'delete' %></li>
          </ul>
        </li>
       <% else %>
        <li><%= link_to 'Sign up', new_user_path %></li>
        <li><%= link_to 'Sign in', new_session_path %></li>
       <% end %>
    </ul>
  </section>
</nav>

<% else %>
  <nav class="top-bar" data-topbar>
    <ul class="title-area">
      <li class="name">
        <h1><%= link_to 'OpenTable', root_path %></h1>
      </li>
      <li class='toggle-topbar menu-icon'><a href="#"><span>Menu</span></a></li>
    </ul>

    <section class="top-bar-section">
      <!-- Right Nav Section -->
      <ul class="right">
        <% if current_user %>
  	      <li class="has-dropdown">
  	        <%= link_to 'My Account', '#' %>	
  	        <ul class="dropdown">
  	        	<li><%= link_to 'My Reservations', current_user %></li>
              <li><%= link_to 'Edit Settings', edit_user_path(current_user) %></li>
  	          <li><%= link_to 'Sign out', session_path(current_user), method: 'delete' %></li>
  	        </ul>
  	      </li>
  	     <% else %>
  	     	<li><%= link_to 'Sign up', new_user_path %></li>
  	     	<li><%= link_to 'Sign in', new_session_path %></li>
  	     <% end %>
      </ul>

      <!-- Left Nav Section -->
      <ul class="left">
        <li><%= link_to 'Restaurant Directory', restaurants_all_path %></li>
      </ul>
    </section>
  </nav>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    
    <%= render 'layouts/header' %>
    <% if flash[:notice] %>
      <div data-alert class='alert-box success radius'><%= flash[:notice] %></div>
    <% elsif flash[:alert] %>
      <div data-alert class='alert-box alert radius'><%= flash[:alert] %></div>
    <% end %>
    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>